# Funding for your project — orientation partenariats Armée Française

github: [teremuhamblin]

custom:
  - https://www.defense.gouv.fr/terre
  - https://www.defense.gouv.fr/air
  - https://www.defense.gouv.fr/marine
  - https://www.defense.gouv.fr/reserve
  - https://www.defense.gouv.fr/ema/civilo-militaire
